apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-manifest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chritter/argo_manifest
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
